// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SakilaAPI.Data;

#nullable disable

namespace SakilaAPI.Data.Migrations
{
    [DbContext(typeof(SakilaContext))]
    [Migration("20250418112434_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SakilaAPI.Models.Actor", b =>
                {
                    b.Property<ushort>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("actor_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("ActorId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.HasKey("ActorId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LastName" }, "idx_actor_last_name");

                    b.ToTable("actor", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.ActorInfo", b =>
                {
                    b.Property<ushort>("ActorId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("actor_id");

                    b.Property<string>("FilmInfo")
                        .HasColumnType("text")
                        .HasColumnName("film_info");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.ToTable((string)null);

                    b.ToView("actor_info", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Address", b =>
                {
                    b.Property<ushort>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("address_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("AddressId"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address2");

                    b.Property<ushort>("CityId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("city_id");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("district");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("postal_code");

                    b.HasKey("AddressId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CityId" }, "idx_fk_city_id");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Category", b =>
                {
                    b.Property<byte>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("CategoryId"));

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.City", b =>
                {
                    b.Property<ushort>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("city_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("CityId"));

                    b.Property<string>("City1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<ushort>("CountryId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.HasKey("CityId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "idx_fk_country_id");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Country", b =>
                {
                    b.Property<ushort>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("country_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("CountryId"));

                    b.Property<string>("Country1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.HasKey("CountryId")
                        .HasName("PRIMARY");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Customer", b =>
                {
                    b.Property<ushort>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("customer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("CustomerId"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<ushort>("AddressId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("LastUpdate"));

                    b.Property<byte>("StoreId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("store_id");

                    b.HasKey("CustomerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AddressId" }, "idx_fk_address_id");

                    b.HasIndex(new[] { "StoreId" }, "idx_fk_store_id");

                    b.HasIndex(new[] { "LastName" }, "idx_last_name");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.CustomerList", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<ushort>("Id")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(91)
                        .HasColumnType("varchar(91)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("notes")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<byte>("Sid")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("SID");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("zip code");

                    b.ToTable((string)null);

                    b.ToView("customer_list", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Film", b =>
                {
                    b.Property<ushort>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("film_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("FilmId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<byte>("LanguageId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("language_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<ushort?>("Length")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("length");

                    b.Property<byte?>("OriginalLanguageId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("original_language_id");

                    b.Property<string>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('G','PG','PG-13','R','NC-17')")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("'G'");

                    b.Property<short?>("ReleaseYear")
                        .HasColumnType("year")
                        .HasColumnName("release_year");

                    b.Property<byte>("RentalDuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("rental_duration")
                        .HasDefaultValueSql("'3'");

                    b.Property<decimal>("RentalRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("rental_rate")
                        .HasDefaultValueSql("'4.99'");

                    b.Property<decimal>("ReplacementCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("replacement_cost")
                        .HasDefaultValueSql("'19.99'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.HasKey("FilmId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LanguageId" }, "idx_fk_language_id");

                    b.HasIndex(new[] { "OriginalLanguageId" }, "idx_fk_original_language_id");

                    b.HasIndex(new[] { "Title" }, "idx_title");

                    b.ToTable("film", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.FilmActor", b =>
                {
                    b.Property<ushort>("ActorId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("actor_id");

                    b.Property<ushort>("FilmId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("film_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.HasKey("ActorId", "FilmId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "FilmId" }, "idx_fk_film_id");

                    b.ToTable("film_actor", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.FilmCategory", b =>
                {
                    b.Property<ushort>("FilmId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("film_id");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.HasKey("FilmId", "CategoryId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "CategoryId" }, "fk_film_category_category");

                    b.ToTable("film_category", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.FilmList", b =>
                {
                    b.Property<string>("Actors")
                        .HasColumnType("text")
                        .HasColumnName("actors");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<ushort?>("Fid")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("FID")
                        .HasDefaultValueSql("'0'");

                    b.Property<ushort?>("Length")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("length");

                    b.Property<decimal?>("Price")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("price")
                        .HasDefaultValueSql("'4.99'");

                    b.Property<string>("Rating")
                        .HasColumnType("enum('G','PG','PG-13','R','NC-17')")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("'G'");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.ToTable((string)null);

                    b.ToView("film_list", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.FilmText", b =>
                {
                    b.Property<short>("FilmId")
                        .HasColumnType("smallint")
                        .HasColumnName("film_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("FilmId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Title", "Description" }, "idx_title_description")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.ToTable("film_text", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Inventory", b =>
                {
                    b.Property<uint>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("mediumint unsigned")
                        .HasColumnName("inventory_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("InventoryId"));

                    b.Property<ushort>("FilmId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("film_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<byte>("StoreId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("store_id");

                    b.HasKey("InventoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FilmId" }, "idx_fk_film_id")
                        .HasDatabaseName("idx_fk_film_id1");

                    b.HasIndex(new[] { "StoreId", "FilmId" }, "idx_store_id_film_id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Language", b =>
                {
                    b.Property<byte>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("language_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("LanguageId"));

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.HasKey("LanguageId")
                        .HasName("PRIMARY");

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.NicerButSlowerFilmList", b =>
                {
                    b.Property<string>("Actors")
                        .HasColumnType("text")
                        .HasColumnName("actors");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<ushort?>("Fid")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("FID")
                        .HasDefaultValueSql("'0'");

                    b.Property<ushort?>("Length")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("length");

                    b.Property<decimal?>("Price")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("price")
                        .HasDefaultValueSql("'4.99'");

                    b.Property<string>("Rating")
                        .HasColumnType("enum('G','PG','PG-13','R','NC-17')")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("'G'");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("title");

                    b.ToTable((string)null);

                    b.ToView("nicer_but_slower_film_list", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Payment", b =>
                {
                    b.Property<ushort>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("payment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("amount");

                    b.Property<ushort>("CustomerId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("LastUpdate"));

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date");

                    b.Property<int?>("RentalId")
                        .HasColumnType("int")
                        .HasColumnName("rental_id");

                    b.Property<byte>("StaffId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("staff_id");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RentalId" }, "fk_payment_rental");

                    b.HasIndex(new[] { "CustomerId" }, "idx_fk_customer_id");

                    b.HasIndex(new[] { "StaffId" }, "idx_fk_staff_id");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rental_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<ushort>("CustomerId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("customer_id");

                    b.Property<uint>("InventoryId")
                        .HasColumnType("mediumint unsigned")
                        .HasColumnName("inventory_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime")
                        .HasColumnName("rental_date");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("return_date");

                    b.Property<byte>("StaffId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("staff_id");

                    b.HasKey("RentalId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "idx_fk_customer_id")
                        .HasDatabaseName("idx_fk_customer_id1");

                    b.HasIndex(new[] { "InventoryId" }, "idx_fk_inventory_id");

                    b.HasIndex(new[] { "StaffId" }, "idx_fk_staff_id")
                        .HasDatabaseName("idx_fk_staff_id1");

                    b.HasIndex(new[] { "RentalDate", "InventoryId", "CustomerId" }, "rental_date")
                        .IsUnique();

                    b.ToTable("rental", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.SalesByFilmCategory", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("category");

                    b.Property<decimal?>("TotalSales")
                        .HasPrecision(27, 2)
                        .HasColumnType("decimal(27,2)")
                        .HasColumnName("total_sales");

                    b.ToTable((string)null);

                    b.ToView("sales_by_film_category", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.SalesByStore", b =>
                {
                    b.Property<string>("Manager")
                        .HasMaxLength(91)
                        .HasColumnType("varchar(91)")
                        .HasColumnName("manager");

                    b.Property<string>("Store")
                        .HasMaxLength(101)
                        .HasColumnType("varchar(101)")
                        .HasColumnName("store");

                    b.Property<decimal?>("TotalSales")
                        .HasPrecision(27, 2)
                        .HasColumnType("decimal(27,2)")
                        .HasColumnName("total_sales");

                    b.ToTable((string)null);

                    b.ToView("sales_by_store", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Staff", b =>
                {
                    b.Property<byte>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("staff_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("StaffId"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<ushort>("AddressId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("address_id");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<string>("Password")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("password")
                        .UseCollation("utf8mb4_bin");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("blob")
                        .HasColumnName("picture");

                    b.Property<byte>("StoreId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("store_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("username");

                    b.HasKey("StaffId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AddressId" }, "idx_fk_address_id")
                        .HasDatabaseName("idx_fk_address_id1");

                    b.HasIndex(new[] { "StoreId" }, "idx_fk_store_id")
                        .HasDatabaseName("idx_fk_store_id1");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.StaffList", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(91)
                        .HasColumnType("varchar(91)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<byte>("Sid")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("SID");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("zip code");

                    b.ToTable((string)null);

                    b.ToView("staff_list", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Store", b =>
                {
                    b.Property<byte>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("store_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("StoreId"));

                    b.Property<ushort>("AddressId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastUpdate"));

                    b.Property<byte>("ManagerStaffId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("manager_staff_id");

                    b.HasKey("StoreId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AddressId" }, "idx_fk_address_id")
                        .HasDatabaseName("idx_fk_address_id2");

                    b.HasIndex(new[] { "ManagerStaffId" }, "idx_unique_manager")
                        .IsUnique();

                    b.ToTable("store", (string)null);
                });

            modelBuilder.Entity("SakilaAPI.Models.Address", b =>
                {
                    b.HasOne("SakilaAPI.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .IsRequired()
                        .HasConstraintName("fk_address_city");

                    b.Navigation("City");
                });

            modelBuilder.Entity("SakilaAPI.Models.City", b =>
                {
                    b.HasOne("SakilaAPI.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("fk_city_country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SakilaAPI.Models.Customer", b =>
                {
                    b.HasOne("SakilaAPI.Models.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_address");

                    b.HasOne("SakilaAPI.Models.Store", "Store")
                        .WithMany("Customers")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_store");

                    b.Navigation("Address");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SakilaAPI.Models.Film", b =>
                {
                    b.HasOne("SakilaAPI.Models.Language", "Language")
                        .WithMany("FilmLanguages")
                        .HasForeignKey("LanguageId")
                        .IsRequired()
                        .HasConstraintName("fk_film_language");

                    b.HasOne("SakilaAPI.Models.Language", "OriginalLanguage")
                        .WithMany("FilmOriginalLanguages")
                        .HasForeignKey("OriginalLanguageId")
                        .HasConstraintName("fk_film_language_original");

                    b.Navigation("Language");

                    b.Navigation("OriginalLanguage");
                });

            modelBuilder.Entity("SakilaAPI.Models.FilmActor", b =>
                {
                    b.HasOne("SakilaAPI.Models.Actor", "Actor")
                        .WithMany("FilmActors")
                        .HasForeignKey("ActorId")
                        .IsRequired()
                        .HasConstraintName("fk_film_actor_actor");

                    b.HasOne("SakilaAPI.Models.Film", "Film")
                        .WithMany("FilmActors")
                        .HasForeignKey("FilmId")
                        .IsRequired()
                        .HasConstraintName("fk_film_actor_film");

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("SakilaAPI.Models.FilmCategory", b =>
                {
                    b.HasOne("SakilaAPI.Models.Category", "Category")
                        .WithMany("FilmCategories")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("fk_film_category_category");

                    b.HasOne("SakilaAPI.Models.Film", "Film")
                        .WithMany("FilmCategories")
                        .HasForeignKey("FilmId")
                        .IsRequired()
                        .HasConstraintName("fk_film_category_film");

                    b.Navigation("Category");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("SakilaAPI.Models.Inventory", b =>
                {
                    b.HasOne("SakilaAPI.Models.Film", "Film")
                        .WithMany("Inventories")
                        .HasForeignKey("FilmId")
                        .IsRequired()
                        .HasConstraintName("fk_inventory_film");

                    b.HasOne("SakilaAPI.Models.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("fk_inventory_store");

                    b.Navigation("Film");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SakilaAPI.Models.Payment", b =>
                {
                    b.HasOne("SakilaAPI.Models.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_payment_customer");

                    b.HasOne("SakilaAPI.Models.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payment_rental");

                    b.HasOne("SakilaAPI.Models.Staff", "Staff")
                        .WithMany("Payments")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("fk_payment_staff");

                    b.Navigation("Customer");

                    b.Navigation("Rental");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SakilaAPI.Models.Rental", b =>
                {
                    b.HasOne("SakilaAPI.Models.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_rental_customer");

                    b.HasOne("SakilaAPI.Models.Inventory", "Inventory")
                        .WithMany("Rentals")
                        .HasForeignKey("InventoryId")
                        .IsRequired()
                        .HasConstraintName("fk_rental_inventory");

                    b.HasOne("SakilaAPI.Models.Staff", "Staff")
                        .WithMany("Rentals")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("fk_rental_staff");

                    b.Navigation("Customer");

                    b.Navigation("Inventory");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SakilaAPI.Models.Staff", b =>
                {
                    b.HasOne("SakilaAPI.Models.Address", "Address")
                        .WithMany("Staff")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_staff_address");

                    b.HasOne("SakilaAPI.Models.Store", "Store")
                        .WithMany("Staff")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("fk_staff_store");

                    b.Navigation("Address");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SakilaAPI.Models.Store", b =>
                {
                    b.HasOne("SakilaAPI.Models.Address", "Address")
                        .WithMany("Stores")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_store_address");

                    b.HasOne("SakilaAPI.Models.Staff", "ManagerStaff")
                        .WithOne("StoreNavigation")
                        .HasForeignKey("SakilaAPI.Models.Store", "ManagerStaffId")
                        .IsRequired()
                        .HasConstraintName("fk_store_staff");

                    b.Navigation("Address");

                    b.Navigation("ManagerStaff");
                });

            modelBuilder.Entity("SakilaAPI.Models.Actor", b =>
                {
                    b.Navigation("FilmActors");
                });

            modelBuilder.Entity("SakilaAPI.Models.Address", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Staff");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("SakilaAPI.Models.Category", b =>
                {
                    b.Navigation("FilmCategories");
                });

            modelBuilder.Entity("SakilaAPI.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SakilaAPI.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("SakilaAPI.Models.Customer", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SakilaAPI.Models.Film", b =>
                {
                    b.Navigation("FilmActors");

                    b.Navigation("FilmCategories");

                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("SakilaAPI.Models.Inventory", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SakilaAPI.Models.Language", b =>
                {
                    b.Navigation("FilmLanguages");

                    b.Navigation("FilmOriginalLanguages");
                });

            modelBuilder.Entity("SakilaAPI.Models.Rental", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SakilaAPI.Models.Staff", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Rentals");

                    b.Navigation("StoreNavigation");
                });

            modelBuilder.Entity("SakilaAPI.Models.Store", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Inventories");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
